### ISSUE TITLE
Handling cookies set on clientside when using encryption

### ISSUE THREAD

**Issue by jonathan-s** [stefanesser/suhosin#100]
When you have encryption enabled as described here: https://suhosin.org/stories/howtos.html#cookie-encryption if you set a cookie client side the plugin is preventing you from reading those unencrypted cookies. 

This is not obvious reading the documentation so it would be great if this was added to the documentation. It's a rather elusive bug if you are setting things on the client side and then expecting it to show up on the backend.

**Comment by bef** [comment]
There is some documentation here: https://suhosin.org/stories/configuration.html#suhosin-cookie-cryptlist
as well as the `LANGUAGE` cookie in the howto example.

Do you have any suggestion what exactly might be useful to add to the documentation for better understanding the whitelist/blacklist feature?

**Comment by jonathan-s** [comment]
For the how to I would add the following. See bold marked. 

Cookie values can be encrypted transparently. Cookies are stored within the client's web browser and are transferred with the HTTP header. By encrypting cookies, you may protect your application against numerous attacks, such as

* cookie tampering: An attacker may try to guess other reasonable cookie values to attack the application.
* inter-application cookie usage: Incorrectly configured applications may have the same session storage, e.g. sessions all stored in /tmp. A cookie from one application can never be reused for another application as long as the encryption key differs.
* knowing what exactly is stored in the cookie

However:

* Cookies are still stored on the client and should not be trusted unchecked in any case.
* Even with encryption, please do not store secret data in cookies, e.g. passwords.
* An attacker may try to reuse an old cookie.
* The cookie size is slightly bigger with encryption than without encryption. Some applications make use of huge cookies in the first place and may not work correctly if the encrypted cookie is too big for the web browser.
* **To be able to read cookies in the backend that are set with javascript on the clientside you will have to add them to `suhosin.cookie.plainlist`. Otherwise they won't be found.**

This feature is disabled by default. You can specify which cookies to encrypt (cryptlist) or which to exempt (plainlist).

For the other entry I would add 

In case some cookies should not be encrypted this is a comma separated list of cookies that do not get encrypted. All other cookies will be encrypted. **Please note that cookies that are set clientside with javascript need to be added to the plainlist for the backend to read them**

**Comment by jonathan-s** [comment]
That would be clear enough for me.

**Comment by bef** [comment]
Thank you for your suggestions. The documentation has been extended appropriately.
