### ISSUE TITLE
Disable or uninstall Suhosin? 404 for everything

### ISSUE THREAD

**Issue by UbuntuJohn** [stefanesser/suhosin#102]
I installed Suhosin the other day and since then I haven't been able to access my localhost, it seems to have overwritten port 80 and so I must constantly stop apache2 and run on port 81, but then Suhosin starts back up some how and runs, blocking me from localhost:81. Everything draws a 404 when it's running even if a page actually exists. 

I'm on Mac OS X 10.7.5 and I've been using MAMP for years.

Any help is appreciated!

**Comment by bef** [comment]
Hi UbuntuJohn. Your problem appears to be unrelated to Suhosin.
