### ISSUE TITLE
Ini section

### ISSUE THREAD

**Issue by szepeviktor** [stefanesser/suhosin#106]
Should Suhosin have a section in suhosin.ini?

```ini
[suhosin]
```

**Comment by bef** [comment]
Maybe. Are there any disadvantages to having no [suhosin] section?

**Comment by szepeviktor** [comment]
I do not know.
I think it won't hurt adding one.
Please consider it.

**Comment by bef** [comment]
It appears to have been lost somewhere on the way. But `[suhosin]` is back now.

**Comment by szepeviktor** [comment]
:)
