### ISSUE TITLE
suhosin should not restrict on cli access

### ISSUE THREAD

**Issue by chrcoluk** [stefanesser/suhosin#110]
I think suhosin should only be used when php is loaded from the web, but not when php is run on cli called via cron.  I respect this is my opinion so the request is to add a setting such as suhosin.cli.enable set to on or off by the administrator.

I assume this can be detected by this status "attacker 'REMOTE_ADDR not set"

**Comment by bef** [comment]
You can easily use PHP-CLI without Suhosin by omitting the `extension=suhosin.so` line in your `php.ini`. E.g. on Debian, the CLI version has its own configuration directory `/etc/php5/cli`.

**Comment by chrcoluk** [comment]
I tried that already it was not present in the main php.ini but was present in the fpm container. Suhosin appears in phpinfo, but does nothing.  Nothing blocked and nothing logged. It only works when in the main php.ini file.

**Comment by bef** [comment]
Correct. I don't see a reason why suhosin would need to be disabled when it does not have to be loaded in the first place for CLI execution.

Another solution would be to just wrap your php cli handler with a short shell script that does something like `php-cli -n -c /etc/php-cli.ini "$@"`.

**Comment by chrcoluk** [comment]
I already setup fpm now to use a new php.ini just appending -c /path/to/config to the start command. :)

Works fine, I just have to make sure I dont forget there is now a second ini file for it.  Thanks for the tip on the wrapper.
