### ISSUE TITLE
Licensed unter the PHP license and is not (the) PHP (software project)

### ISSUE THREAD

**Issue by waja** [stefanesser/suhosin#48]
Hi there,

most of your code is licensed under the ´[PHP License, version 3.01](http://www.php.net/license/3_01.txt)´.

There is a discussion over there in the [Debian](http://www.debian.org/about/) project, if software is redistributable if it´s licensed under this license and it comes not from the "PHP Group". While in the first place this looks like just a Debian (and maybe other distributions) [problem](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752886#63), it may also affect this software project itself.

A valuation of the Debian FTP-Team, not only affecting redistribution in Debian, can be found here:

https://lists.debian.org/debian-legal/2005/08/msg00128.html
https://lists.debian.org/debian-legal/2006/02/msg00215.html

It would be cool, if you could relicense your work to a license which allows others to redistribute your work and don´t gives potential troubles yourself.

A close license to your actual one [maybe](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752886#63):
- BSD
- MIT/Expat

Many thanks, Jan.

**Comment by mcmidget** [comment]
Hi people..
Is there any update about this subject?

**Comment by bef** [comment]
Some Suhosin code was taken from PHP licensed code and then modified to fit the problem. As a result, the whole Suhosin code was licensed with the PHP license, regardless if the PHP license may or may not enforce derived code to be licensed this way.

In case some parts of this license is not applicable to the Suhosin code, the  corresponding section invalidates implicitly and the rest of the license remains intact, as does the underlying idea.

I hope that clarifies things.

**Comment by bef** [comment]
I think the issue has been explained in detail an can be closed. If in doubt, please have a look at the common sense interpretation of the PHP license as provided with Suhosin7, which has exactly the same license issue as Suhosin: https://github.com/sektioneins/suhosin7/blob/master/LICENSE
