### ISSUE TITLE
Unable to open logfile

### ISSUE THREAD

**Issue by infosec7** [stefanesser/suhosin#77]
Hello,

I have this error:

[Wed Feb 11 15:07:56 2015] [error] [client xxx.xxx.xxx.xxx] ALERT-SIMULATION - U
nable to open logfile: /var/log/apache2/suhosin.log (attacker 'xxx.xxx.xxx.xxx',
 file '/var/www/phpinfo.php', line 1)

Debian GNU/Linux 7.8 (wheezy) / 64
Apache/2.2.22 (Debian) Server built: Dec 23 2014 22:48:29

root@server:~# php5 -v
PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
with Suhosin v0.9.37.1, Copyright (c) 2007-2014, by SektionEins GmbH

root@server:~# php5 -m | grep  Suhosin
Suhosin
root@server:~#

/etc/php5/mods-available/suhosin.ini

; =====================
; Logging Configuration
; =====================
;suhosin.log.syslog = S_ALL & ~S_SQL
;
suhosin.log.syslog.facility = LOG_USER
suhosin.log.syslog.priority = LOG_ALERT
;
;suhosin.log.sapi = 0
;suhosin.log.stdout = 0
;
suhosin.log.file = 511
suhosin.log.file.name = /var/log/apache2/suhosin.log
suhosin.log.file.time = On
...
...

# stat /var/log/apache2/suhosin.log
...
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    4/     adm)
...

# stat /var/log/apache2/error.log
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (    4/     adm)

root@server:~# cat /etc/rsyslog.d/suhosin.conf
LOG_USER* -/var/log/apache2/suhosin.log
& ~

Any ideas?

Thanks

**Comment by bef** [comment]
Suhosin opens/writes the its logfile on demand with current user rights. E.g.
```
$ ps axuf |grep apache
root      11027  0.0  1.2 476072  6284 ?        Ssl  Feb09   0:19 /usr/sbin/apache2 -k start
www-data  12420  0.0  0.2 476424  1332 ?        Sl   Feb09   0:00  \_ /usr/sbin/apache2 -k start
www-data  12421  0.0  0.2 476424  1336 ?        Sl   Feb09   0:00  \_ /usr/sbin/apache2 -k start
www-data  12424  0.0  0.2 476424  1364 ?        Sl   Feb09   0:01  \_ /usr/sbin/apache2 -k start
www-data  12425  0.0  0.2 476424  1272 ?        Sl   Feb09   0:00  \_ /usr/sbin/apache2 -k start
www-data  12428  0.0  0.2 476424  1276 ?        Sl   Feb09   0:00  \_ /usr/sbin/apache2 -k start
www-data  43235  0.0  0.2 476424  1284 ?        Sl   Feb09   0:00  \_ /usr/sbin/apache2 -k start
www-data  43708  0.0  0.2 476424  1144 ?        Sl   Feb09   0:00  \_ /usr/sbin/apache2 -k start
```
In this example, most processes are owned by user `www-data`. As a result this user needs access to the suhosin logfile.
Apache logfiles work differently.

**Comment by infosec7** [comment]
Hello,

I still have the same issue ....

root@server:~# ls -l /var/log/apache2/suhosin.log
-rw-r----- 1 www-data www-data 1276 Feb 11 23:09 /var/log/apache2/suhosin.log

[Thu Feb 12 13:02:49 2015] [error] [client xxx.xxx.xxx.xxx] ALERT-SIMULATION - U
nable to open logfile: /var/log/apache2/suhosin.log (attacker 'xxx.xxx.xxx.xxx',
 file '/var/www/phpinfo.php', line 1)

Best Regards

**Comment by infosec7** [comment]
root@server:~# grep 'www-data' /etc/group
www-data:x:33:root

**Comment by bef** [comment]
Example:
```
# touch /var/log/apache2/suhosin.log
# chown root:www-data /var/log/apache2/suhosin.log
# chmod 664 /var/log/apache2/suhosin.log
```
Please see `man chmod` and `man chown` for further documentation.

**Comment by heximcz** [comment]
chmod 755 /var/log/apache2/

modify apache logrotate (debian jessie in this exaple):

/var/log/apache2/*.log {
  daily
  missingok
  rotate 14
  compress
  delaycompress
  notifempty
  create 640 root adm
  sharedscripts
  postrotate
                if /etc/init.d/apache2 status > /dev/null ; then \
                    /etc/init.d/apache2 reload > /dev/null; \
                fi;
                touch /var/log/apache2/suhosin-alert.log; \
                chown root:www-data /var/log/apache2/suhosin-alert.log; \
                chmod 666 /var/log/apache2/suhosin-alert.log; \
  endscript
  prerotate
    if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
      run-parts /etc/logrotate.d/httpd-prerotate; \
    fi; \
  endscript
}

on last:
logrotate -f /etc/logrotate.d/apache2

Enjoy!
