### ISSUE TITLE
php 7.0 no work

### ISSUE THREAD

**Issue by andykimpe** [stefanesser/suhosin#81]
http://blog.famillecollet.com/post/2015/03/25/PHP-7.0-as-Software-Collection

yum --enablerepo=remi,remi-test install php70 php70-php php70-php-devel

wget https://github.com/stefanesser/suhosin/archive/master.zip

unzip master.zip

rm -f master.zip

cd suhosin-master

scl enable php70 'phpize'

<code>Configuring for:

PHP Api Version:         20131218

Zend Module Api No:      20141001

Zend Extension Api No:   320140815</code>

scl enable php70 './configure'

<code>checking for grep that handles long lines and -e... /bin/grep
...
make: *** [suhosin.lo] Erreur 1</code>

scl enable php70  'php --version'
<code>PHP 7.0.0-dev (cli) (built: Apr  3 2015 08:22:25) 

Copyright (c) 1997-2015 The PHP Group

Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies</code>

I know that this version is still in development but it would be nice to make what is compatible with suhosin before its official release

**Comment by stefanesser** [comment]
We are waiting until there is an official PHP 7 Alpha or Beta before we start porting. The internals of PHP changed quite a bit between PHP 5 and PHP 7 and therefore a lot of code needs to be redone.

**Comment by andykimpe** [comment]
lol php 7.0 alpha 2

http://php.net/archive/2015.php#id2015-06-25-1

**Comment by quantumpacket** [comment]
@andykimpe I would wait until beta1 (July 9th) since it will be a feature freeze and the only changes will be stability fixes. Alphas can still change the internals of PHP, betas can't. PHP7 won't be officially released until Nov 12th, so we still got a lot of time.

**Comment by stefanesser** [comment]
It is unlikely that you will see any PHP 7 support in our public Git repository before nearly all of it is ported. Otherwise we will be flooded with people complaining that it does not work, yet.

**Comment by szepeviktor** [comment]
@stefanesser Thank you for your hard work.
As PHP 7 is imminent do you have a beta of suhosin to test?

**Comment by keppler** [comment]
After 8 release candidates, PHP 7.0.0 is being released today (2015-12-03). Most (or all) download repositories already have this archive available.
As Suhosin does a very great job and is extremely valuable in shared hosting scenarios, I appreciate support for PHP 7. :)

**Comment by bef** [comment]
@keppler: I could not agree more. However we try to slip in a few actually paying jobs while developing secure open source software.

Suhosin for PHP 7 will take place here: https://github.com/sektioneins/suhosin7

**Comment by onlime** [comment]
+1 we will greatly appreciate as well! Keep up the good work, Stefan.

**Comment by laukstein** [comment]
When planned to add PHP 7 support?

**Comment by bef** [comment]
PHP7 support is a work in progress and takes place in a separate repository: https://github.com/sektioneins/suhosin7

Its corresponding issue tracker will open once the code base is stable enough for beta testing. Please be patient.

**Comment by iEFdev** [comment]
@bef, Would it be helpful to you to get the terminal output of a failed compilation, to _(hopefully)_ get more/other errors to work with? …from misc environments.

_I kept my log from Dec 25 when I tried to install it._

    // OS X 10.7.5, gcc-5.3.0, php-7.0.1

**Comment by bef** [comment]
@iEFdev Thank you for the offer. However it does not make any sense to try to compile suhosin-0.9.x with PHP7. There have been significant changes to PHP with PHP7, most notably the internal string handling. This is why Suhosin7 is an entirely separate project.

**Comment by iEFdev** [comment]
@bef, Yes it was before I saw the new one, and since suhosin7 told me not to, I skipped that one. :) Was just a thought. But, you can get the output log (2x) of that one instead.
