### ISSUE TITLE
Uninstall and/or disable Suhosin on PHP5.6 Ubuntu 14.04

### ISSUE THREAD

**Issue by goodreason** [stefanesser/suhosin#87]
"Suhosin is a PHP security extension that attempts to protect against potential bugs in your application's PHP code. Suhosin may break functionality in your apps. By using this extension, you recognize that you may increase the burden on your developers and negatively affect your users as a result of breakage."

I am prepared to install Suhosin but I would not take the risk unless I know I can uninstall or disable without much drama.

I am not a developer or coder so I need everything explained to me carefully.

Thank you.

**Comment by bef** [comment]
The Suhosin extension can easily be activated in your php.ini by adding `extension=suhosin.so`.
In Ubuntu you can easily install a Suhosin package - see https://suhosin.org/stories/install.html#installing-on-debian-and-ubuntu (e.g. option 2 for testing) - and activate using the command `php5enmod suhosin`.   Equivalently `php5dismod suhosin` disables suhosin.
Configuration is done in `/etc/php5/mods-available/suhosin.ini`.
You can check for suhosin with `phpinfo();` in apache (or any other webserver), or with `php5 -v` for php-cli.

**Comment by goodreason** [comment]
Thank you bef.
