### ISSUE TITLE
Docs error in https://suhosin.org/stories/howtos.html#whitelist-vs-blacklist

### ISSUE THREAD

**Issue by rainerjung** [stefanesser/suhosin#93]
The page

https://suhosin.org/stories/howtos.html#whitelist-vs-blacklist

contains the following example config snippet under the heading "Blacklisting":

Now, let's disable a few dangerous functions and allow the rest:

suhosin.executor.func.blacklist = assert,unserialize,exec,popen,proc_open,passthru,shell_exec,system,hail,parse_str,mt_srand
suhosin.executor.eval.whitelist = assert,unserialize,exec,popen,proc_open,passthru,shell_exec,system,hail,parse_str,mt_srand

The seconds line must use the property suhosin.executor.eval.blacklist instead of suhosin.executor.eval.whitelist.

Futhermore I question the use of suhosin.executor.func.blacklist plus suhosin.executor.eval.blacklist setting to the same value, because after the eval the functions must still be called and then the suhosin.executor.func.blacklist applies. So IMHO such a dublication of config doesn't make much sense. I would expect a typical useful config would e.g. have a blacklist for func and a whitelist for eval. Or a func blacklist and a longer eval blacklist.

Can you confirm, that any function already forbidden by func blalist (or absense in an existing func whitelist) can't automatically be called by eval either? Or is this reasoning flawed?

Sorry for putting 2 things into one issue, but they are tightly related.

Thanks!

Rainer

**Comment by bef** [comment]
The documentation example was indeed somewhat misleading and has been corrected.

The function blacklist/whitelist always takes precedence. An eval whitelist/blacklist, if defined, will protect function calls within eval() in addition to the function whitelist/blacklist. Of course, any combination of function whitelist and eval blacklist or function blacklist and eval whitelist is perfectly fine, too.
