### ISSUE TITLE
shared hosting

### ISSUE THREAD

**Issue by muhsayd** [stefanesser/suhosin#95]
How to disallow customers to connect with the usernames of other customers using suhosin.sql.user_postfix
How to set it ?
Could I set it to a dynamic value to reflect the cpanel username for ever website on the server ?

**Comment by bef** [comment]
`suhosin.sql.user_prefix` and `suhosin.sql.user_postfix` effectively change the username of `mysqli_connect` and other sql connect functions by prepending/appending the user_prefix and user_postfix respectively.

Example:
```
suhosin.sql.user_prefix = foo_
suhosin.sql.user_postfix = _bar
```
Then in your PHP code:
```
$link = mysqli_connect("127.0.0.1", "user", "my_password", "my_db");
```
The resulting username would be `foo_user_bar`.

Both prefix and postfix can be set on a per-directory basis, e.g. with .htaccess or equivalent.
