### ISSUE TITLE
can suhosin work with php5-cgi libapache2-mod-fcgid

### ISSUE THREAD

**Issue by joshS95** [stefanesser/suhosin#96]
Hello,

I have a VPS with Debian 8/64 and Apache 2.4

I have this congig:

php5 libapache2-mod-php5 apache2-mpm-prefork php5-suhosin-extension

It is working well.

I want to install SDPY module
https://developers.google.com/speed/spdy/mod_spdy/php

and I have to change to this config

php5 php5-cgi libapache2-mod-fcgid apache2-mpm-worker 

Can php5-suhosin-extension work with php5-cgi?

Thanks and have a nice day!

Josh

**Comment by bef** [comment]
I don't see why not. I fact, some of the unit tests run with php-cgi by default.
In your case I would suggest php-fpm, which is compatible with suhosin as well.
