### ISSUE TITLE
ini priority for debian/ubuntu

### ISSUE THREAD

**Issue by ogmueller** [stefanesser/suhosin#97]
would it be possible to add a priority comment in the default suhosin.ini (like all other php extensions have) to support debian/ubuntu php5enmod command

currently it looks like:
   1 
   2 extension=suhosin.so
   3
   4 ; =====================
   5 ; Logging Configuration
   6 ; =====================

but it would be nice to have something like the gd.ini:
  1 ; configuration for php GD module
  2 ; priority=20
  3 extension=gd.so

this will enable debian/ubuntu to load the extensions in the "correct" order. whatever is the correct one.

**Comment by bef** [comment]
see #88
